// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.SettingsServiceV2.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class IKeyValueEntity
    {
        /// <summary>
        /// Initializes a new instance of the IKeyValueEntity class.
        /// </summary>
        public IKeyValueEntity()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the IKeyValueEntity class.
        /// </summary>
        public IKeyValueEntity(string value = default(string), IList<OverrideValue> overrideProperty = default(IList<OverrideValue>), IList<string> types = default(IList<string>), bool? isDuplicated = default(bool?), IList<string> repositoryNames = default(IList<string>), string rowKey = default(string), string eTag = default(string))
        {
            Value = value;
            OverrideProperty = overrideProperty;
            Types = types;
            IsDuplicated = isDuplicated;
            RepositoryNames = repositoryNames;
            RowKey = rowKey;
            ETag = eTag;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "override")]
        public IList<OverrideValue> OverrideProperty { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "types")]
        public IList<string> Types { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDuplicated")]
        public bool? IsDuplicated { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "repositoryNames")]
        public IList<string> RepositoryNames { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rowKey")]
        public string RowKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "eTag")]
        public string ETag { get; set; }

    }
}
