// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.SettingsServiceV2.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class KeyValueToUpdate
    {
        /// <summary>
        /// Initializes a new instance of the KeyValueToUpdate class.
        /// </summary>
        public KeyValueToUpdate()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the KeyValueToUpdate class.
        /// </summary>
        public KeyValueToUpdate(bool forced, string rowKey = default(string), string value = default(string))
        {
            RowKey = rowKey;
            Value = value;
            Forced = forced;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "rowKey")]
        public string RowKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "forced")]
        public bool Forced { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
