// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.SettingsServiceV2.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ServiceEntity
    {
        /// <summary>
        /// Initializes a new instance of the ServiceEntity class.
        /// </summary>
        public ServiceEntity()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ServiceEntity class.
        /// </summary>
        public ServiceEntity(string name = default(string), string repositoryId = default(string))
        {
            Name = name;
            RepositoryId = repositoryId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "repositoryId")]
        public string RepositoryId { get; set; }

    }
}
