// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.SettingsServiceV2.Client.AutorestClient.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for UpdateSettingsStatus.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum UpdateSettingsStatus
    {
        [EnumMember(Value = "Ok")]
        Ok,
        [EnumMember(Value = "JsonFormarIncorrrect")]
        JsonFormarIncorrrect,
        [EnumMember(Value = "OutOfDate")]
        OutOfDate,
        [EnumMember(Value = "InternalError")]
        InternalError,
        [EnumMember(Value = "NotFound")]
        NotFound,
        [EnumMember(Value = "HasDuplicated")]
        HasDuplicated,
        [EnumMember(Value = "AlreadyExists")]
        AlreadyExists,
        [EnumMember(Value = "InvalidInput")]
        InvalidInput
    }
    internal static class UpdateSettingsStatusEnumExtension
    {
        internal static string ToSerializedValue(this UpdateSettingsStatus? value)
        {
            return value == null ? null : ((UpdateSettingsStatus)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this UpdateSettingsStatus value)
        {
            switch( value )
            {
                case UpdateSettingsStatus.Ok:
                    return "Ok";
                case UpdateSettingsStatus.JsonFormarIncorrrect:
                    return "JsonFormarIncorrrect";
                case UpdateSettingsStatus.OutOfDate:
                    return "OutOfDate";
                case UpdateSettingsStatus.InternalError:
                    return "InternalError";
                case UpdateSettingsStatus.NotFound:
                    return "NotFound";
                case UpdateSettingsStatus.HasDuplicated:
                    return "HasDuplicated";
                case UpdateSettingsStatus.AlreadyExists:
                    return "AlreadyExists";
                case UpdateSettingsStatus.InvalidInput:
                    return "InvalidInput";
            }
            return null;
        }

        internal static UpdateSettingsStatus? ParseUpdateSettingsStatus(this string value)
        {
            switch( value )
            {
                case "Ok":
                    return UpdateSettingsStatus.Ok;
                case "JsonFormarIncorrrect":
                    return UpdateSettingsStatus.JsonFormarIncorrrect;
                case "OutOfDate":
                    return UpdateSettingsStatus.OutOfDate;
                case "InternalError":
                    return UpdateSettingsStatus.InternalError;
                case "NotFound":
                    return UpdateSettingsStatus.NotFound;
                case "HasDuplicated":
                    return UpdateSettingsStatus.HasDuplicated;
                case "AlreadyExists":
                    return UpdateSettingsStatus.AlreadyExists;
                case "InvalidInput":
                    return UpdateSettingsStatus.InvalidInput;
            }
            return null;
        }
    }
}
